// Note icon catalog — mirrors the web app's EMOJI_OPTIONS / ICON_OPTIONS so the
// same icon model ({ kind:'emoji'|'icon', value|name, color }) round-trips between
// web and mobile. Icon names are the web's keys, mapped to lucide-react-native.
import {
  Activity,
  AlarmClock,
  Archive,
  Award,
  Banknote,
  Bell,
  Book,
  Bookmark,
  Box,
  Brain,
  Briefcase,
  Bug,
  Building2,
  CalendarDays,
  Camera,
  CheckCircle2,
  Circle,
  Clipboard,
  Cloud,
  Code2,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Dumbbell,
  Eye,
  FileText,
  Flag,
  Flame,
  Folder,
  Gift,
  Globe,
  GraduationCap,
  Hash,
  Headphones,
  Heart,
  Home,
  Image as ImageIcon,
  Inbox,
  KeyRound,
  Landmark,
  Layers,
  Lightbulb,
  Link,
  ListTodo,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  MessageSquare,
  Monitor,
  Moon,
  Music,
  Palette,
  Paperclip,
  PenLine,
  Phone,
  Pin,
  Plane,
  Play,
  Puzzle,
  Rocket,
  Save,
  Scissors,
  Server,
  Settings,
  Shield,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  Trophy,
  User,
  Wallet,
  Wrench,
  Zap,
} from 'lucide-react-native';

export const ICON_COLOR_PRESETS = [
  '#ffffff', '#9ca3af', '#60a5fa', '#34d399', '#fbbf24', '#f87171',
  '#a78bfa', '#f472b6', '#2dd4bf', '#fb923c', '#c084fc', '#94a3b8',
];

export const EMOJI_OPTIONS = [
  '📝', '📌', '📎', '📁', '📂', '📄', '📚', '📖', '🔖', '✅', '⭐', '✨',
  '🔥', '💡', '🎯', '🚀', '🧠', '💭', '💬', '🔒', '🔑', '🧾', '📊', '📈',
  '💼', '🏠', '🌱', '🌙', '☀️', '⚡', '🎨', '🎵', '📷', '🗺️', '🧩', '🛠️',
  '💻', '🧪', '📦', '🗃️', '🕒', '📅', '🏷️', '❤️', '💎', '🍀', '🌊', '🏆',
  '🍎', '☕', '🍕', '✈️', '🚗', '🏋️', '🎮', '🎬', '📡', '🌍', '🔮', '🪄',
  '😀', '😄', '🙂', '😎', '🤓', '🤔', '🙌', '👏', '🙏', '💪', '👀', '✍️',
  '💯', '❗', '❓', '➕', '➖', '🔁', '🔔', '🔕', '📣', '📍', '🚩', '🧭',
  '🗂️', '🗒️', '📓', '📔', '📕', '📗', '📘', '📙', '📰', '🧷', '✂️', '🖊️',
  '🖋️', '✏️', '📐', '📏', '🔎', '🧮', '💰', '💳', '🕹️', '🎧', '🎤', '🏢',
  '🏛️', '🏫', '🏥', '🏖️', '⛰️', '🌆', '🌌', '🌈', '❄️', '🌸', '🍄', '🥑',
  '🍓', '🍔', '🍜', '🍱', '🧁', '🚲', '🚆', '🚢', '⌛', '⏳', '⏰', '🧘',
  '🛌', '🩺', '💊', '🔬', '🧬', '🛰️', '🧱', '🧰', '⚙️', '🧲', '🪙',
];

export const ICON_OPTIONS = [
  { name: 'activity', Icon: Activity },
  { name: 'alarm', Icon: AlarmClock },
  { name: 'folder', Icon: Folder },
  { name: 'fileText', Icon: FileText },
  { name: 'book', Icon: Book },
  { name: 'bookmark', Icon: Bookmark },
  { name: 'archive', Icon: Archive },
  { name: 'award', Icon: Award },
  { name: 'banknote', Icon: Banknote },
  { name: 'bell', Icon: Bell },
  { name: 'brain', Icon: Brain },
  { name: 'bug', Icon: Bug },
  { name: 'building', Icon: Building2 },
  { name: 'inbox', Icon: Inbox },
  { name: 'briefcase', Icon: Briefcase },
  { name: 'home', Icon: Home },
  { name: 'calendar', Icon: CalendarDays },
  { name: 'camera', Icon: Camera },
  { name: 'checkCircle', Icon: CheckCircle2 },
  { name: 'clipboard', Icon: Clipboard },
  { name: 'cloud', Icon: Cloud },
  { name: 'todo', Icon: ListTodo },
  { name: 'star', Icon: Star },
  { name: 'heart', Icon: Heart },
  { name: 'sparkles', Icon: Sparkles },
  { name: 'flame', Icon: Flame },
  { name: 'zap', Icon: Zap },
  { name: 'lightbulb', Icon: Lightbulb },
  { name: 'rocket', Icon: Rocket },
  { name: 'palette', Icon: Palette },
  { name: 'image', Icon: ImageIcon },
  { name: 'music', Icon: Music },
  { name: 'coffee', Icon: Coffee },
  { name: 'compass', Icon: Compass },
  { name: 'cpu', Icon: Cpu },
  { name: 'creditCard', Icon: CreditCard },
  { name: 'dumbbell', Icon: Dumbbell },
  { name: 'eye', Icon: Eye },
  { name: 'flag', Icon: Flag },
  { name: 'gift', Icon: Gift },
  { name: 'globe', Icon: Globe },
  { name: 'graduation', Icon: GraduationCap },
  { name: 'headphones', Icon: Headphones },
  { name: 'message', Icon: MessageSquare },
  { name: 'mail', Icon: Mail },
  { name: 'tag', Icon: Tag },
  { name: 'hash', Icon: Hash },
  { name: 'link', Icon: Link },
  { name: 'paperclip', Icon: Paperclip },
  { name: 'lock', Icon: Lock },
  { name: 'key', Icon: KeyRound },
  { name: 'shield', Icon: Shield },
  { name: 'user', Icon: User },
  { name: 'wallet', Icon: Wallet },
  { name: 'landmark', Icon: Landmark },
  { name: 'layers', Icon: Layers },
  { name: 'map', Icon: MapIcon },
  { name: 'mapPin', Icon: MapPin },
  { name: 'monitor', Icon: Monitor },
  { name: 'moon', Icon: Moon },
  { name: 'penLine', Icon: PenLine },
  { name: 'phone', Icon: Phone },
  { name: 'pin', Icon: Pin },
  { name: 'plane', Icon: Plane },
  { name: 'play', Icon: Play },
  { name: 'puzzle', Icon: Puzzle },
  { name: 'save', Icon: Save },
  { name: 'scissors', Icon: Scissors },
  { name: 'server', Icon: Server },
  { name: 'shopping', Icon: ShoppingBag },
  { name: 'smile', Icon: Smile },
  { name: 'sun', Icon: Sun },
  { name: 'target', Icon: Target },
  { name: 'terminal', Icon: Terminal },
  { name: 'code', Icon: Code2 },
  { name: 'database', Icon: Database },
  { name: 'box', Icon: Box },
  { name: 'settings', Icon: Settings },
  { name: 'trophy', Icon: Trophy },
  { name: 'wrench', Icon: Wrench },
  { name: 'circle', Icon: Circle },
];

export const ICON_COMPONENTS = ICON_OPTIONS.reduce((acc, option) => {
  acc[option.name] = option.Icon;
  return acc;
}, {});
